services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    volumes:
      - ./backend:/code
    command: flask run --host=0.0.0.0
    ports:
      - 5000:5000
    environment:
      - FLASK_DEBUG=1
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    volumes:
    - ./frontend:/code
    command: npm run dev
    ports:
      - 3000:3000
  proxy:
    image: nginx
    restart: always
    volumes: 
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 8080:80
